### ISSUE TITLE
Guide titles should be action oriented

### ISSUE THREAD

**Issue by cangencer** [hazelcast-guides/guides-site#9]
Update guide titles so they reflect the objective of the guide, otherwise they're vague i.e. Hazelcast on Kubernetes could include how to operate it and many other concerns. Same goes about the subtitle - it should indicate what the goal is.

Hazelcast with Spring Boot -> Use Hazelcast in a Spring Boot Application
Subtitle: Create a basic Spring Boot application which can utilize Hazelcast

Hazelcast Client With Quarkus -> Connect To Hazelcast From A Quarkus Application
Subtitle: Create a basic Quarkus application which connects to a Hazelcast cluster.

Hazelcast On Kubernetes -> Deploy Hazelcast on Kubernetes
Subtitle: Learn how to deploy Hazelcast on a Kubernetes environment

etc

**Comment by enozcan** [comment]
I agree that titles/subtitles on the homepage should follow a common pattern which is not exactly how they are now. But I also think it would be better to keep the titles brief like "X and Hazelcast" to denote that Hazelcast is being integrated into X in this guide - like, for instance, Spring guides do: https://spring.io/guides. However about the subtitles, I agree with you and we better make them action oriented. WDTY? (cc: @leszko)

**Comment by cangencer** [comment]
As you can see on the Spring ones, they're all "objective" oriented. X and Hazelcast doesn't really tell you what the goal is.

![image](https://user-images.githubusercontent.com/510278/101133737-a1ace400-3609-11eb-9add-f71f424c23fc.png)

They also have "topical" guides which are much longer (1 hour in length) - these are not in tutorial format but cover a wide range of topics.

![image](https://user-images.githubusercontent.com/510278/101133762-ad000f80-3609-11eb-90c2-a9f662b6be92.png)

**Comment by enozcan** [comment]
OK I got the point. A few of them, namely Spring Boot with Docker, Spring Boot Kubernetes etc. made me think that way but obviously these are just a few. Let me create a pr and discuss further there.
